require("tgnvsctn.plugins-setup")

require("tgnvsctn.core.options")
require("tgnvsctn.core.keymaps")
require("tgnvsctn.core.colorscheme")

require("tgnvsctn.plugins.nvim-cmp")
require("tgnvsctn.plugins.lsp.mason")
require("tgnvsctn.plugins.lsp.lspsaga")
require("tgnvsctn.plugins.lsp.lspconfig")
require("tgnvsctn.plugins.lsp.null-ls")
require("tgnvsctn.plugins.treesitter")
require("tgnvsctn.plugins.comment")
require("tgnvsctn.plugins.nvim-tree")
require("tgnvsctn.plugins.feline")
require("tgnvsctn.plugins.telescope")
require("tgnvsctn.plugins.autopairs")
require("tgnvsctn.plugins.gitsigns")
require("tgnvsctn.plugins.which-key")
require("tgnvsctn.plugins.indent-blankline")
require("tgnvsctn.plugins.fidget")
